name: Build and push Debezium images for new tags to quay.io
on:
  push:
    tags:
      - '**'

jobs:
  build-tags-postgres:
    uses: ./.github/workflows/build.yml
    with:
      DEBEZIUM_CONNECTOR: postgres
      DEBEZIUM_VERSION_UPSTREAM: ${{ github.ref_name }}.Final
      DEBEZIUM_VERSION_DOWNSTREAM: ${{ github.ref_name }}.ER1
    secrets:
      REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
      REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  build-tags-mongodb:
    uses: ./.github/workflows/build.yml
    with:
      DEBEZIUM_CONNECTOR: mongodb
      DEBEZIUM_VERSION_UPSTREAM: ${{ github.ref_name }}.Final
      DEBEZIUM_VERSION_DOWNSTREAM: ${{ github.ref_name }}.ER1
    secrets:
      REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
      REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  build-tags-mysql:
    uses: ./.github/workflows/build.yml
    with:
      DEBEZIUM_CONNECTOR: mysql
      DEBEZIUM_VERSION_UPSTREAM: ${{ github.ref_name }}.Final
      DEBEZIUM_VERSION_DOWNSTREAM: ${{ github.ref_name }}.ER1
    secrets:
      REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
      REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  build-tags-sqlserver:
    uses: ./.github/workflows/build.yml
    with:
      DEBEZIUM_CONNECTOR: sqlserver
      DEBEZIUM_VERSION_UPSTREAM: ${{ github.ref_name }}.Final
      DEBEZIUM_VERSION_DOWNSTREAM: ${{ github.ref_name }}.ER1
    secrets:
      REGISTRY_SERVER: ${{ secrets.REGISTRY_SERVER }}
      REGISTRY_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
